baseImageOverrides:
  github.com/imjasonh/kontain.me/cmd/ko: golang
  github.com/imjasonh/kontain.me/cmd/buildpack: gcr.io/buildpacks/builder
  github.com/imjasonh/kontain.me/cmd/viz: gcr.io/kontainme/graphviz

  # Works with any of:
  # - packs/samples:v3alpha2
  # - heroku/buildpacks
  # - cloudfoundry/cnb
  github.com/imjasonh/kontain.me/cmd/api: packs/samples:v3alpha2
